[workspace]
resolver = "3"
members = [
    "crates/cherry-pit-app",
    "crates/cherry-pit-core",
    "crates/cherry-pit-gateway",
    "crates/cherry-pit-merger",
    "crates/cherry-pit-projection",
    "crates/cherry-pit-wq",
    "crates/cherry-pit-storage",
    "crates/cherry-pit-web",
    "crates/non-exhaustive-check",
    "crates/pardosa-cherry-pit-projection",
    "crates/pardosa-cherry-pit-test-support",
]

[workspace.package]
edition = "2024"
rust-version = "1.98"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/acje/cherry-pit"
repository = "https://github.com/acje/cherry-pit"
authors = ["Mattilsynet"]

[workspace.dependencies]
proc-macro2 = "1"
syn = { version = "3", features = ["full", "extra-traits"] }
toml = "1"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
uuid = { version = "1", features = ["v7", "serde"] }
jiff = { version = "0.2", features = ["serde"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
scc = "3"
futures-util = "0.3"
axum = { version = "0.8", default-features = false, features = ["http1", "http2", "tokio", "json", "ws"] }
tower-http = { version = "0.7", features = ["limit", "trace"] }
bytes = "1"
percent-encoding = "2"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "http2", "json", "gzip"] }
sha2 = "0.11"
zstd = { version = "0.14", default-features = false }
arc-swap = { version = "1", default-features = false }
tracing = "0.1"
thiserror = "2"
criterion = { version = "0.8", default-features = false }
fastrand = "2"
gethostname = "1"
rustix = { version = "1.1.4", default-features = false, features = ["process", "std"] }
cherry-pit-core = { path = "crates/cherry-pit-core", version = "0.1.0" }
cherry-pit-gateway = { path = "crates/cherry-pit-gateway", version = "0.1.0" }
cherry-pit-projection = { path = "crates/cherry-pit-projection", version = "0.1.0" }
cherry-pit-web = { path = "crates/cherry-pit-web", version = "0.1.0" }
cherry-pit-app = { path = "crates/cherry-pit-app", version = "0.1.0" }
cherry-pit-merger = { path = "crates/cherry-pit-merger", version = "0.1.0" }
pardosa = { git = "https://github.com/acje/pardosa", rev = "49ea5ec42a782aa9303b0e6eab2659d59d181e69", version = "0.5.5" }
tokio-util = { version = "0.7", default-features = false }
tempfile = "3"
proptest = "1"
trybuild = "1"
tokio-tungstenite = "0.30"

[profile.dev]
debug = 1

[profile.test]
debug = 1

[profile.release]
lto = true
strip = true
codegen-units = 1
overflow-checks = true

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
as_underscore = "warn"
as_pointer_underscore = "warn"
clear_with_drain = "warn"
dbg_macro = "warn"
iter_on_empty_collections = "warn"
iter_on_single_items = "warn"
iter_with_drain = "warn"
literal_string_with_formatting_args = "warn"
needless_collect = "warn"
search_is_some = "warn"
string_lit_as_bytes = "warn"
todo = "warn"
unimplemented = "warn"
unused_result_ok = "warn"
