//! README generation for ADR domain directories, stale archive, and
//! the top-level hub.
//!
//! Generates all `README.md` files from parsed ADR records on every
//! `adr-fmt` invocation.  Generated files carry a marker comment so
//! contributors know not to edit them by hand.
//!
//! Before overwriting any existing file, the generator verifies that
//! the file's first line contains the generated-file marker.  If the
//! marker is absent (indicating a hand-edited file), the write is
//! skipped and a warning is emitted.

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use crate::config::Config;
use crate::model::{AdrId, AdrRecord, DomainDir, RelVerb};

const MARKER: &str = "<!-- Generated by adr-fmt. Do not edit. -->\n";

/// Trimmed marker for first-line comparison (without trailing `\n`).
const MARKER_TRIMMED: &str = "<!-- Generated by adr-fmt. Do not edit. -->";

// ── public entry point ──────────────────────────────────────────────

/// Generate all README files: one per domain, the stale archive, and
/// the top-level hub.
pub fn generate_all(
    records: &[AdrRecord],
    domain_dirs: &[DomainDir],
    adr_root: &Path,
    config: &Config,
) {
    generate_top_level(domain_dirs, records, adr_root, config);
    for dir in domain_dirs {
        let domain_records: Vec<&AdrRecord> = records
            .iter()
            .filter(|r| r.id.prefix == dir.prefix && !r.is_stale)
            .collect();
        generate_domain(dir, &domain_records, records);
    }
    generate_stale(records, adr_root, config);
}

// ── safe write ──────────────────────────────────────────────────────

/// Write `content` to `path`, but only if the file either does not
/// exist or already carries the generated-file marker on its first
/// line.  Protects hand-edited files from accidental overwrite.
fn safe_write(path: &Path, content: &str) {
    if path.exists() {
        match fs::read_to_string(path) {
            Ok(existing) => {
                let first_line = existing.lines().next().unwrap_or("");
                if first_line.trim_end() != MARKER_TRIMMED {
                    eprintln!(
                        "warning: refusing to overwrite {} — missing generated-file marker",
                        path.display()
                    );
                    return;
                }
            }
            Err(e) => {
                eprintln!(
                    "warning: cannot read {} for marker check, skipping overwrite: {e}",
                    path.display()
                );
                return;
            }
        }
    }

    fs::write(path, content).unwrap_or_else(|e| {
        eprintln!("error: failed to write {}: {e}", path.display());
    });
}

// ── top-level README ────────────────────────────────────────────────

fn generate_top_level(
    dirs: &[DomainDir],
    records: &[AdrRecord],
    adr_root: &Path,
    config: &Config,
) {
    let mut out = String::from(MARKER);
    out.push_str("\n# Architecture Decision Records\n\n");

    out.push_str("| Domain | Prefix | ADRs | Directory |\n");
    out.push_str("|--------|--------|------|-----------|\n");

    for dir in dirs {
        let count = records
            .iter()
            .filter(|r| r.id.prefix == dir.prefix && !r.is_stale)
            .count();
        let name = dir_name(dir);
        writeln!(
            out,
            "| {} | {} | {count} | [{name}]({name}/) |",
            dir.name, dir.prefix,
        )
        .unwrap();
    }

    // Stale count
    let stale_count = records.iter().filter(|r| r.is_stale).count();
    if stale_count > 0 {
        writeln!(
            out,
            "\n[Stale archive]({stale_dir}/) — {stale_count} archived ADR(s).",
            stale_dir = config.stale.directory,
        )
        .unwrap();
    }

    out.push_str("\nGoverned by [GOVERNANCE.md](GOVERNANCE.md).\n");

    let path = adr_root.join("README.md");
    safe_write(&path, &out);
}

// ── domain README ───────────────────────────────────────────────────

fn generate_domain(dir: &DomainDir, domain_records: &[&AdrRecord], all_records: &[AdrRecord]) {
    let mut out = String::from(MARKER);

    // Header
    writeln!(out, "\n# {} — Architecture Decision Records\n", dir.name).unwrap();
    writeln!(out, "{}\n", dir.description).unwrap();
    out.push_str("Governed by [GOVERNANCE.md](../GOVERNANCE.md).\n");

    // Index table
    out.push_str("\n## Index\n\n");
    out.push_str("| # | Title | Tier | Status | References |\n");
    out.push_str("|---|-------|------|--------|------------|\n");

    let mut sorted: Vec<&&AdrRecord> = domain_records.iter().collect();
    sorted.sort_by_key(|r| r.id.number);

    for record in &sorted {
        let file_name = record
            .file_path
            .file_name()
            .map(|n| n.to_string_lossy())
            .unwrap_or_default();
        let title = record.title.as_deref().unwrap_or("(untitled)");
        let tier = record
            .tier
            .map(|t| format!("{t:?}"))
            .unwrap_or_else(|| "?".into());
        let status = format_status_short(record);
        let refs = format_references(record);

        writeln!(
            out,
            "| [{id}]({file_name}) | {title} | {tier} | {status} | {refs} |",
            id = record.id,
        )
        .unwrap();
    }

    // Dependency tree
    out.push_str("\n## Dependency Tree\n\n");
    let tree = build_flat_forest(domain_records);
    out.push_str("```\n");
    out.push_str(&tree);
    out.push_str("```\n");

    // Cross-domain references
    let cross = collect_cross_domain_refs(domain_records, all_records);
    if !cross.is_empty() {
        out.push_str("\n## Cross-Domain References\n\n");
        out.push_str("| ADR | Target | Verb |\n");
        out.push_str("|-----|--------|------|\n");
        for (source_id, target_id, verb) in &cross {
            writeln!(out, "| {source_id} | {target_id} | {verb} |").unwrap();
        }
    }

    let path = dir.path.join("README.md");
    safe_write(&path, &out);
}

// ── stale README ────────────────────────────────────────────────────

fn generate_stale(records: &[AdrRecord], adr_root: &Path, config: &Config) {
    let stale_records: Vec<&AdrRecord> = records.iter().filter(|r| r.is_stale).collect();

    let stale_dir = adr_root.join(&config.stale.directory);
    if !stale_dir.is_dir() {
        // No stale directory — nothing to generate
        return;
    }

    let mut out = String::from(MARKER);
    out.push_str("\n# Stale Architecture Decision Records\n\n");
    out.push_str(
        "Archived ADRs that are no longer active: Rejected, Deprecated, or Superseded.\n\n",
    );
    out.push_str("Governed by [GOVERNANCE.md](../GOVERNANCE.md).\n");

    if stale_records.is_empty() {
        out.push_str("\n*No stale ADRs.*\n");
    } else {
        // Group by domain prefix, using config to resolve domain names
        let domain_name_for: HashMap<&str, &str> = config
            .domains
            .iter()
            .map(|d| (d.prefix.as_str(), d.name.as_str()))
            .collect();

        // Collect unique prefixes in order
        let mut prefixes: Vec<&str> = stale_records
            .iter()
            .map(|r| r.id.prefix.as_str())
            .collect::<HashSet<_>>()
            .into_iter()
            .collect();
        prefixes.sort();

        for prefix in &prefixes {
            let domain_name = domain_name_for
                .get(prefix)
                .copied()
                .unwrap_or("Unknown Domain");
            writeln!(out, "\n## {domain_name}\n").unwrap();
            out.push_str("| # | Title | Status |\n");
            out.push_str("|---|-------|--------|\n");

            let mut domain_stale: Vec<&&AdrRecord> = stale_records
                .iter()
                .filter(|r| r.id.prefix.as_str() == *prefix)
                .collect();
            domain_stale.sort_by_key(|r| r.id.number);

            for record in &domain_stale {
                let file_name = record
                    .file_path
                    .file_name()
                    .map(|n| n.to_string_lossy())
                    .unwrap_or_default();
                let title = record.title.as_deref().unwrap_or("(untitled)");
                let status = format_status_short(record);

                writeln!(
                    out,
                    "| [{id}]({file_name}) | {title} | {status} |",
                    id = record.id,
                )
                .unwrap();
            }
        }
    }

    let path = stale_dir.join("README.md");
    safe_write(&path, &out);
}

// ── flat-forest dependency tree ─────────────────────────────────────

/// Build a flat-forest text representation of the dependency tree.
///
/// Rules:
/// - Self-references are filtered (they are tree root markers, not
///   parent edges).
/// - Primary parent = first non-self `References` target within the
///   same domain.
/// - ADRs with a self-reference and no other in-domain references are
///   explicit roots.
/// - ADRs with only `Supersedes` (no `References`) are roots.
/// - Cycle detection via visited set — cyclic ADRs become roots.
/// - Dangling primary parent (target not in records) → root.
/// - ADRs with zero relationships go into an "Independent" group.
fn build_flat_forest(records: &[&AdrRecord]) -> String {
    let id_set: HashSet<&AdrId> = records.iter().map(|r| &r.id).collect();

    // Map each ADR to its primary parent (first non-self References target in same domain).
    let mut parent_of: HashMap<&AdrId, &AdrId> = HashMap::new();
    for record in records {
        if let Some(primary) = first_in_domain_reference(record, &id_set) {
            parent_of.insert(&record.id, primary);
        }
    }

    // Detect cycles: walk each chain, mark visited.
    // Trade-off: all cycle participants become independent roots
    // rather than showing partial structure.  Acceptable because
    // cycles are governance violations (S003 warns about them).
    let mut acyclic_parents: HashMap<&AdrId, &AdrId> = HashMap::new();
    for record in records {
        let id = &record.id;
        if !parent_of.contains_key(id) {
            continue;
        }
        // Walk the chain from this node upward.
        let mut visited: HashSet<&AdrId> = HashSet::new();
        let mut cursor = id;
        let mut is_cyclic = false;
        while let Some(p) = parent_of.get(cursor) {
            if !visited.insert(p) {
                // Cycle detected — break all participants out as roots.
                is_cyclic = true;
                break;
            }
            cursor = p;
        }
        if !is_cyclic {
            acyclic_parents.insert(id, parent_of[id]);
        }
    }

    // Build children map.
    let mut children_of: HashMap<&AdrId, Vec<&AdrId>> = HashMap::new();
    for (child, parent) in &acyclic_parents {
        children_of.entry(parent).or_default().push(child);
    }
    // Sort children by number.
    for kids in children_of.values_mut() {
        kids.sort_by_key(|id| id.number);
    }

    // Identify roots (no acyclic parent) and independent (no relationships at all).
    let mut roots: Vec<&AdrRecord> = Vec::new();
    let mut independent: Vec<&AdrRecord> = Vec::new();

    let mut sorted: Vec<&&AdrRecord> = records.iter().collect();
    sorted.sort_by_key(|r| r.id.number);

    for record in &sorted {
        if acyclic_parents.contains_key(&record.id) {
            continue; // Has a parent, will appear as a child.
        }
        // Self-referencing ADRs are explicit roots.
        // ADRs with no relationships and no children are independent.
        if record.relationships.is_empty()
            && !record.is_self_referencing
            && !children_of.contains_key(&record.id)
        {
            independent.push(record);
        } else {
            roots.push(record);
        }
    }

    let mut out = String::new();

    // Build lookup for title by id.
    let title_map: HashMap<&AdrId, &str> = records
        .iter()
        .map(|r| (&r.id, r.title.as_deref().unwrap_or("(untitled)")))
        .collect();

    for root in &roots {
        render_node(&root.id, &title_map, &children_of, &mut out, "", true);
    }

    if !independent.is_empty() {
        if !roots.is_empty() {
            out.push('\n');
        }
        out.push_str("Independent:\n");
        for record in &independent {
            let title = record.title.as_deref().unwrap_or("(untitled)");
            writeln!(out, "  {} {title}", record.id).unwrap();
        }
    }

    out
}

/// Find the first non-self `References` target that exists within the
/// same domain.  Self-references are filtered because they are tree
/// root markers, not parent edges.
fn first_in_domain_reference<'a>(
    record: &'a AdrRecord,
    domain_ids: &HashSet<&'a AdrId>,
) -> Option<&'a AdrId> {
    record
        .relationships
        .iter()
        .filter(|rel| rel.verb == RelVerb::References)
        .map(|rel| &rel.target)
        .filter(|target| *target != &record.id) // skip self-references
        .find(|target| domain_ids.contains(target))
}

/// Recursively render a tree node with box-drawing connectors.
fn render_node(
    id: &AdrId,
    titles: &HashMap<&AdrId, &str>,
    children: &HashMap<&AdrId, Vec<&AdrId>>,
    out: &mut String,
    prefix: &str,
    is_root: bool,
) {
    let title = titles.get(id).copied().unwrap_or("(untitled)");
    if is_root {
        writeln!(out, "{id} {title}").unwrap();
    }

    if let Some(kids) = children.get(id) {
        let last_idx = kids.len() - 1;
        for (i, child) in kids.iter().enumerate() {
            let is_last = i == last_idx;
            let connector = if is_last { "└── " } else { "├── " };
            let child_title = titles.get(child).copied().unwrap_or("(untitled)");
            writeln!(out, "{prefix}{connector}{child} {child_title}").unwrap();

            let child_prefix = if is_last {
                format!("{prefix}    ")
            } else {
                format!("{prefix}│   ")
            };
            render_node(child, titles, children, out, &child_prefix, false);
        }
    }
}

// ── cross-domain references ─────────────────────────────────────────

fn collect_cross_domain_refs(
    domain_records: &[&AdrRecord],
    all_records: &[AdrRecord],
) -> Vec<(String, String, String)> {
    let all_ids: HashSet<&AdrId> = all_records.iter().map(|r| &r.id).collect();
    let mut refs = Vec::new();

    let mut sorted: Vec<&&AdrRecord> = domain_records.iter().collect();
    sorted.sort_by_key(|r| r.id.number);

    for record in &sorted {
        for rel in &record.relationships {
            if rel.verb.is_reverse() {
                continue;
            }
            // Skip self-references
            if rel.target == record.id {
                continue;
            }
            if rel.target.prefix != record.id.prefix && all_ids.contains(&rel.target) {
                refs.push((
                    record.id.to_string(),
                    rel.target.to_string(),
                    rel.verb.to_string(),
                ));
            }
        }
    }
    refs
}

// ── helpers ─────────────────────────────────────────────────────────

fn dir_name(dir: &DomainDir) -> &str {
    dir.path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("unknown")
}

fn format_status_short(record: &AdrRecord) -> String {
    match &record.status {
        Some(crate::model::Status::Draft) => "Draft".into(),
        Some(crate::model::Status::Proposed) => "Proposed".into(),
        Some(crate::model::Status::Accepted) => "Accepted".into(),
        Some(crate::model::Status::Amended { .. }) => "Amended".into(),
        Some(crate::model::Status::Rejected) => "Rejected".into(),
        Some(crate::model::Status::Deprecated) => "Deprecated".into(),
        Some(crate::model::Status::SupersededBy(id)) => format!("Superseded by {id}"),
        Some(crate::model::Status::Invalid(s)) => s.clone(),
        None => "?".into(),
    }
}

fn format_references(record: &AdrRecord) -> String {
    let refs: Vec<String> = record
        .relationships
        .iter()
        .filter(|r| !r.verb.is_reverse())
        .filter(|r| r.target != record.id) // skip self-references in display
        .map(|r| {
            if r.verb == RelVerb::Supersedes {
                format!("Supersedes {}", r.target)
            } else {
                r.target.to_string()
            }
        })
        .collect();

    if refs.is_empty() {
        if record.is_self_referencing {
            "⊙ (root)".into()
        } else {
            "—".into()
        }
    } else {
        refs.join(", ")
    }
}

// ── tests ───────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{AdrId, Relationship, Status, Tier};
    use std::path::PathBuf;

    fn make_id(prefix: &str, num: u16) -> AdrId {
        AdrId {
            prefix: prefix.into(),
            number: num,
        }
    }

    fn make_record(
        prefix: &str,
        num: u16,
        title: &str,
        rels: Vec<(RelVerb, &str, u16)>,
    ) -> AdrRecord {
        let id = make_id(prefix, num);
        let relationships: Vec<Relationship> = rels
            .into_iter()
            .enumerate()
            .map(|(i, (verb, p, n))| Relationship {
                verb,
                target: make_id(p, n),
                line: 10 + i,
            })
            .collect();

        let is_self_referencing = relationships
            .iter()
            .any(|rel| rel.verb == RelVerb::References && rel.target == id);

        AdrRecord {
            id,
            file_path: PathBuf::from(format!(
                "docs/adr/cherry/{prefix}-{num:04}-test.md"
            )),
            title: Some(title.into()),
            title_line: 1,
            date: Some("2026-04-25".into()),
            date_line: 3,
            last_reviewed: None,
            last_reviewed_line: 0,
            tier: Some(Tier::B),
            tier_line: 5,
            status: Some(Status::Accepted),
            status_line: 8,
            status_raw: Some("Accepted".into()),
            relationships,
            has_related: true,
            has_context: true,
            has_decision: true,
            has_consequences: true,
            has_rejection_rationale: false,
            is_self_referencing,
            is_stale: false,
            max_code_block_lines: 0,
            max_code_block_line: 0,
            code_block_count: 0,
            amendment_dates: vec![],
            related_has_placeholder: false,
        }
    }

    #[test]
    fn self_referencing_adr_is_root() {
        let records = vec![
            make_record("CHE", 1, "Root", vec![(RelVerb::References, "CHE", 1)]),
            make_record("CHE", 2, "Child", vec![(RelVerb::References, "CHE", 1)]),
        ];
        let refs: Vec<&AdrRecord> = records.iter().collect();
        let tree = build_flat_forest(&refs);
        // CHE-0001 self-references → explicit root, CHE-0002 is child
        assert!(tree.starts_with("CHE-0001"), "tree:\n{tree}");
        assert!(tree.contains("CHE-0002 Child"), "tree:\n{tree}");
        // Should NOT be in Independent section
        assert!(!tree.contains("Independent:"), "tree:\n{tree}");
    }

    #[test]
    fn self_reference_only_adr_is_root_not_independent() {
        let records = vec![
            make_record("CHE", 1, "Standalone Root", vec![(RelVerb::References, "CHE", 1)]),
        ];
        let refs: Vec<&AdrRecord> = records.iter().collect();
        let tree = build_flat_forest(&refs);
        assert!(tree.contains("CHE-0001 Standalone Root"), "tree:\n{tree}");
        assert!(!tree.contains("Independent:"), "tree:\n{tree}");
    }

    #[test]
    fn roots_have_no_references() {
        let records = vec![
            make_record("CHE", 1, "Root One", vec![]),
            make_record("CHE", 2, "Root Two", vec![]),
        ];
        let refs: Vec<&AdrRecord> = records.iter().collect();
        let tree = build_flat_forest(&refs);
        // Both are independent (no relationships at all)
        assert!(tree.contains("Independent:"), "tree:\n{tree}");
        assert!(tree.contains("CHE-0001 Root One"), "tree:\n{tree}");
        assert!(tree.contains("CHE-0002 Root Two"), "tree:\n{tree}");
    }

    #[test]
    fn single_parent_chain() {
        let records = vec![
            make_record("CHE", 1, "Root", vec![]),
            make_record("CHE", 2, "Child", vec![(RelVerb::References, "CHE", 1)]),
            make_record("CHE", 3, "Grandchild", vec![(RelVerb::References, "CHE", 2)]),
        ];
        let refs: Vec<&AdrRecord> = records.iter().collect();
        let tree = build_flat_forest(&refs);
        assert!(tree.contains("CHE-0001 Root"), "tree:\n{tree}");
        assert!(tree.contains("CHE-0002 Child"), "tree:\n{tree}");
        assert!(tree.contains("CHE-0003 Grandchild"), "tree:\n{tree}");
        // Root is a root node (has children but no parent)
        assert!(tree.starts_with("CHE-0001"), "tree:\n{tree}");
    }

    #[test]
    fn first_reference_is_primary_parent() {
        let records = vec![
            make_record("CHE", 1, "Parent A", vec![]),
            make_record("CHE", 2, "Parent B", vec![]),
            make_record(
                "CHE",
                3,
                "Multi-ref",
                vec![
                    (RelVerb::References, "CHE", 1),
                    (RelVerb::References, "CHE", 2),
                ],
            ),
        ];
        let refs: Vec<&AdrRecord> = records.iter().collect();
        let tree = build_flat_forest(&refs);
        // CHE-0003 should be under CHE-0001 (first reference)
        let lines: Vec<&str> = tree.lines().collect();
        let root_line = lines.iter().position(|l| l.contains("CHE-0001")).unwrap();
        let child_line = lines.iter().position(|l| l.contains("CHE-0003")).unwrap();
        assert!(
            child_line > root_line,
            "CHE-0003 should appear after CHE-0001 (its primary parent)\ntree:\n{tree}"
        );
    }

    #[test]
    fn cycle_detection_breaks_cycle() {
        let records = vec![
            make_record("CHE", 1, "Alpha", vec![(RelVerb::References, "CHE", 2)]),
            make_record("CHE", 2, "Beta", vec![(RelVerb::References, "CHE", 1)]),
        ];
        let refs: Vec<&AdrRecord> = records.iter().collect();
        let tree = build_flat_forest(&refs);
        // Both should appear (no infinite loop or panic)
        assert!(tree.contains("CHE-0001 Alpha"), "tree:\n{tree}");
        assert!(tree.contains("CHE-0002 Beta"), "tree:\n{tree}");
    }

    #[test]
    fn dangling_primary_parent_becomes_root() {
        let records = vec![make_record(
            "CHE",
            1,
            "Orphan",
            vec![(RelVerb::References, "CHE", 99)],
        )];
        let refs: Vec<&AdrRecord> = records.iter().collect();
        let tree = build_flat_forest(&refs);
        // CHE-0001 references non-existent CHE-0099, so it becomes root
        assert!(tree.contains("CHE-0001 Orphan"), "tree:\n{tree}");
    }

    #[test]
    fn supersedes_only_is_root() {
        let records = vec![
            make_record("CHE", 1, "Old", vec![]),
            make_record(
                "CHE",
                2,
                "New",
                vec![(RelVerb::Supersedes, "CHE", 1)],
            ),
        ];
        let refs: Vec<&AdrRecord> = records.iter().collect();
        let tree = build_flat_forest(&refs);
        // CHE-0002 has only Supersedes (not References), so it's a root
        // CHE-0001 has no relationships at all, so it's independent
        assert!(tree.contains("CHE-0002 New"), "tree:\n{tree}");
    }

    #[test]
    fn independent_adrs_grouped() {
        let records = vec![
            make_record("CHE", 1, "Root", vec![]),
            make_record("CHE", 2, "Child", vec![(RelVerb::References, "CHE", 1)]),
            make_record("CHE", 3, "Loner", vec![]),
        ];
        let refs: Vec<&AdrRecord> = records.iter().collect();
        let tree = build_flat_forest(&refs);
        assert!(tree.contains("Independent:"), "tree:\n{tree}");
        assert!(tree.contains("CHE-0003 Loner"), "tree:\n{tree}");
        // CHE-0001 has children so it's a root, not independent
        assert!(tree.starts_with("CHE-0001"), "tree:\n{tree}");
    }

    #[test]
    fn cross_domain_primary_is_root_in_own_domain() {
        // CHE-0001 references COM-0002 — cross-domain, so no in-domain parent
        let records = vec![make_record(
            "CHE",
            1,
            "Cross-ref",
            vec![(RelVerb::References, "COM", 2)],
        )];
        let refs: Vec<&AdrRecord> = records.iter().collect();
        let tree = build_flat_forest(&refs);
        // Should be a root in CHE domain (cross-domain ref doesn't count)
        assert!(tree.contains("CHE-0001 Cross-ref"), "tree:\n{tree}");
    }

    #[test]
    fn empty_domain_produces_empty_tree() {
        let records: Vec<&AdrRecord> = vec![];
        let tree = build_flat_forest(&records);
        assert!(tree.is_empty(), "tree should be empty: {tree:?}");
    }

    #[test]
    fn multiple_children_sorted() {
        let records = vec![
            make_record("CHE", 1, "Root", vec![]),
            make_record("CHE", 5, "Child C", vec![(RelVerb::References, "CHE", 1)]),
            make_record("CHE", 3, "Child A", vec![(RelVerb::References, "CHE", 1)]),
            make_record("CHE", 7, "Child D", vec![(RelVerb::References, "CHE", 1)]),
        ];
        let refs: Vec<&AdrRecord> = records.iter().collect();
        let tree = build_flat_forest(&refs);
        let lines: Vec<&str> = tree.lines().collect();
        let pos_3 = lines.iter().position(|l| l.contains("CHE-0003")).unwrap();
        let pos_5 = lines.iter().position(|l| l.contains("CHE-0005")).unwrap();
        let pos_7 = lines.iter().position(|l| l.contains("CHE-0007")).unwrap();
        assert!(pos_3 < pos_5 && pos_5 < pos_7, "children should be sorted by number\ntree:\n{tree}");
    }

    #[test]
    fn format_references_empty() {
        let record = make_record("CHE", 1, "Test", vec![]);
        assert_eq!(format_references(&record), "—");
    }

    #[test]
    fn format_references_self_ref_shows_root() {
        let record = make_record("CHE", 1, "Test", vec![(RelVerb::References, "CHE", 1)]);
        let refs = format_references(&record);
        assert_eq!(refs, "⊙ (root)");
    }

    #[test]
    fn format_references_with_supersedes() {
        let record = make_record(
            "CHE",
            2,
            "Test",
            vec![
                (RelVerb::References, "CHE", 1),
                (RelVerb::Supersedes, "CHE", 99),
            ],
        );
        let refs = format_references(&record);
        assert!(refs.contains("CHE-0001"), "refs: {refs}");
        assert!(refs.contains("Supersedes CHE-0099"), "refs: {refs}");
    }

    #[test]
    fn format_status_short_rejected() {
        let mut record = make_record("CHE", 1, "Test", vec![]);
        record.status = Some(Status::Rejected);
        assert_eq!(format_status_short(&record), "Rejected");
    }

    #[test]
    fn safe_write_creates_new_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.md");
        safe_write(&path, "content");
        assert_eq!(fs::read_to_string(&path).unwrap(), "content");
    }

    #[test]
    fn safe_write_overwrites_with_marker() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.md");
        fs::write(&path, format!("{MARKER}old content")).unwrap();
        safe_write(&path, "new content");
        assert_eq!(fs::read_to_string(&path).unwrap(), "new content");
    }

    #[test]
    fn safe_write_refuses_without_marker() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.md");
        fs::write(&path, "# Hand-written README\n").unwrap();
        safe_write(&path, "overwritten");
        // File should be unchanged
        assert_eq!(
            fs::read_to_string(&path).unwrap(),
            "# Hand-written README\n"
        );
    }

    #[test]
    fn safe_write_refuses_empty_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.md");
        fs::write(&path, "").unwrap();
        safe_write(&path, "overwritten");
        assert_eq!(fs::read_to_string(&path).unwrap(), "");
    }

    #[test]
    fn safe_write_handles_marker_with_trailing_whitespace() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.md");
        fs::write(&path, format!("{MARKER_TRIMMED}  \nold")).unwrap();
        safe_write(&path, "new");
        assert_eq!(fs::read_to_string(&path).unwrap(), "new");
    }
}
