//! Guidelines output — human-first governance reference or setup guide.
//!
//! Two paths:
//! - No config: prescriptive quickstart showing how to set up ADR governance.
//! - Config present: complete governance reference derived from config +
//!   hardcoded rule catalog.
//!
//! Output targets humans reading a terminal, not LLMs. Uses headings,
//! bullet lists, and visual hierarchy.

use crate::config::Config;
use crate::model::{RelVerb, Tier};

// ── Public API ─────────────────────────────────────────────────────

/// Print the setup guide when no `adr-fmt.toml` exists.
pub fn print_setup_guide() {
    println!("adr-fmt — ADR Governance Tool");
    println!("═══════════════════════════════");
    println!();
    println!("No adr-fmt.toml found. Create one in your ADR root directory");
    println!("(typically docs/adr/) alongside a GOVERNANCE.md file.");
    println!();
    println!("QUICK START");
    println!("───────────");
    println!();
    println!("  1. Create docs/adr/GOVERNANCE.md (rationale & process)");
    println!("  2. Create docs/adr/adr-fmt.toml:");
    println!();
    println!("     [stale]");
    println!("     directory = \"stale\"");
    println!();
    println!("     [[domains]]");
    println!("     prefix = \"CHE\"");
    println!("     name = \"Cherry\"");
    println!("     directory = \"cherry\"");
    println!("     description = \"Architecture decisions for the cherry-pit project.\"");
    println!("     crates = [\"cherry-pit-core\"]");
    println!();
    println!("  3. Create your first ADR:");
    println!();
    println!("     # CHE-0001. Your First Decision");
    println!();
    println!("     Date: 2026-04-27");
    println!("     Last-reviewed: 2026-04-27");
    println!("     Tier: B");
    println!("     Status: Draft");
    println!();
    println!("     ## Related");
    println!();
    println!("     Root: CHE-0001");
    println!();
    println!("     ## Context");
    println!("     Why this decision exists and what problem it solves.");
    println!();
    println!("     ## Decision");
    println!("     R1 [5]: The specific rule or decision statement");
    println!();
    println!("     ## Consequences");
    println!("     What changes as a result of this decision being made.");
    println!();
    println!("  4. Run: adr-fmt --lint");
    println!();
    println!("MODES");
    println!("─────");
    println!();
    println!("  adr-fmt                       Print governance guidelines (this output)");
    println!("  adr-fmt --lint                Lint all ADRs");
    println!("  adr-fmt --critique CHE-0001   Focal ADR + neighbors");
    println!("  adr-fmt --context crate-name  Decision rules for a crate");
    println!("  adr-fmt --tree [DOMAIN]       Domain tree overview");
    println!();
}

/// Print the full governance reference when config is present.
pub fn print_governance(config: &Config) {
    println!("ADR Governance Reference");
    println!("════════════════════════");
    println!();
    println!("Generated by adr-fmt. Single source of truth for all invariant rules.");
    println!("For rationale and process guidance, see GOVERNANCE.md.");
    println!();

    print_modes();
    print_domains(config);
    print_tiers();
    print_lifecycle();
    print_template();
    print_tagged_rules();
    print_relationships();
    print_naming();
    print_link_rules();
    print_stale(config);
    print_overrides(config);
}

// ── Mode section ───────────────────────────────────────────────────

fn print_modes() {
    println!("MODES");
    println!("─────");
    println!();
    println!("  (default)             Governance guidelines (this document)");
    println!("  --lint                Lint all ADRs, report diagnostics");
    println!("  --critique <ADR_ID>   Focal ADR + direct neighbors (--depth N)");
    println!("  --context <CRATE>     Decision rules applicable to a crate");
    println!("  --tree [DOMAIN]       Domain dependency tree");
    println!();
    println!("  Exit codes: 0 = complete, 1 = infrastructure error");
    println!();
}

// ── Domain section ─────────────────────────────────────────────────

fn print_domains(config: &Config) {
    println!("DOMAINS");
    println!("───────");
    println!();
    for domain in &config.domains {
        let marker = if domain.foundation {
            " ★ foundation"
        } else {
            ""
        };
        println!("  {} ({}){marker}", domain.name, domain.prefix);
        let desc: String = domain
            .description
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ");
        println!("    {desc}");
        println!("    Directory: {}/", domain.directory);
        if !domain.crates.is_empty() {
            println!("    Crates: {}", domain.crates.join(", "));
        }
        println!();
    }
}

// ── Tier section ───────────────────────────────────────────────────

fn print_tiers() {
    println!("TIERS");
    println!("─────");
    println!();
    for tier in Tier::all() {
        println!("  {tier:?} — {}", tier.name());
        println!("    {}", tier.description());
        println!("    Stability: {}", tier.stability());
        println!();
    }
}

// ── Lifecycle section ──────────────────────────────────────────────

fn print_lifecycle() {
    println!("LIFECYCLE");
    println!("─────────");
    println!();
    let statuses = [
        ("Draft", false),
        ("Proposed", false),
        ("Accepted", false),
        ("Rejected", true),
        ("Deprecated", true),
        ("Superseded by PREFIX-NNNN", true),
    ];
    for (name, terminal) in &statuses {
        let marker = if *terminal { " [terminal]" } else { "" };
        println!("  {name}{marker}");
    }
    println!();
    println!("  Terminal states require:");
    println!("    • Move ADR to stale directory");
    println!("    • Add a ## Retirement section");
    println!();
}

// ── Template section ───────────────────────────────────────────────

fn print_template() {
    println!("TEMPLATE");
    println!("────────");
    println!();
    println!("  Required structure:");
    println!();
    println!("    # PREFIX-NNNN. Title");
    println!("    Date: YYYY-MM-DD");
    println!("    Last-reviewed: YYYY-MM-DD");
    println!("    Tier: S | A | B | C | D");
    println!("    Status: Draft | Proposed | Accepted | ...");
    println!("    ## Related");
    println!("    ## Context");
    println!("    ## Decision");
    println!("    ## Consequences");
    println!("    ## Retirement      (stale only)");
    println!();
    println!("  Metadata fields (preamble, before first ## heading):");
    println!("    Date              Creation date (enforced: T002)");
    println!("    Last-reviewed     Most recent review date (enforced: T003)");
    println!("    Tier              Architectural significance S/A/B/C/D (enforced: T004)");
    println!("    Status            Lifecycle state (enforced: T005, T006)");
    println!("    Crates            Optional comma-separated crate list");
    println!();
    println!("  Related section format:");
    println!("    Pipe-separated: Verb: TARGET1, TARGET2 | Verb: TARGET3");
    println!("    Example: Root: CHE-0001 | References: CHE-0002, CHE-0010");
    println!();
    println!("  Rules:");
    println!("    T001  H1 title present and matches PREFIX-NNNN pattern");
    println!("    T002  Date field present (YYYY-MM-DD)");
    println!("    T003  Last-reviewed field present (YYYY-MM-DD)");
    println!("    T004  Tier field present (S/A/B/C/D)");
    println!("    T005  Status present (metadata field or legacy ## Status section)");
    println!("    T005b Dual-status conflict (both preamble field and ## Status section)");
    println!("    T005c Legacy ## Status section — migrate to Status: preamble field");
    println!("    T006  Status is a recognized keyword (rejects Amended)");
    println!("    T007  Related section present with at least one relationship");
    println!("    T008  Context section present");
    println!("    T009  Decision section present");
    println!("    T010  Consequences section present");
    println!("    T011  Code block size limit (max 20 lines)");
    println!("    T014  Section order (Related → Context → Decision → Consequences)");
    println!(
        "    T015  Section word count — signal, not gate. Exceeding the limit"
    );
    println!(
        "          (default 7–100) flags the section for review: it may be"
    );
    println!(
        "          overloaded or genuinely need the space. Override in adr-fmt.toml."
    );
    println!(
        "    T016  Tagged rules — signal, not gate. Limits (max 10 rules,"
    );
    println!(
        "          7–60 words, sequential IDs, layer 1–12) flag ADRs for review."
    );
    println!(
        "          Exceeding max rules may indicate the ADR covers multiple decisions."
    );
    println!();
}

// ── Tagged rules section ───────────────────────────────────────────

fn print_tagged_rules() {
    println!("TAGGED RULES (Decision Section)");
    println!("───────────────────────────────");
    println!();
    println!("  Format:  R1 [N]: Rule statement (7–60 words)");
    println!("           R2 [N]: Next rule statement");
    println!("           Multi-line rules: indent continuation ≥2 spaces");
    println!();
    println!("  [N] = Meadows leverage layer (1–12)");
    println!("    1–3 → S-tier (paradigm/goals/mindset)");
    println!("    4   → A-tier (self-organization)");
    println!("    5–6 → B-tier (rules/information flows)");
    println!("    7–8 → C-tier (feedback loops/delays)");
    println!("    9–12→ D-tier (parameters/buffers)");
    println!();
    println!("  Global ID: PREFIX-NNNN:RN:LN  (e.g., CHE-0042:R1:L5)");
    println!();
    println!("  Constraints (signals — exceeding warrants review, not rejection):");
    println!("    • At least 1 tagged rule per Decision section (all statuses)");
    println!("    • Maximum 10 rules per ADR — more may indicate overloaded scope");
    println!("    • IDs must be sequential (R1, R2, R3 — no gaps)");
    println!("    • Each rule: 7–60 words");
    println!("    • Layer must be 1–12 (Meadows leverage points)");
    println!();
}

// ── Relationship section ───────────────────────────────────────────

fn print_relationships() {
    println!("RELATIONSHIPS");
    println!("─────────────");
    println!();
    println!("  Links point toward the root of the dependency graph.");
    println!("  Reverse links are computed on demand (--critique fan-in).");
    println!();
    println!("  Permitted verbs (3):");
    for verb in RelVerb::permitted() {
        println!("    {verb:<12} {}", verb.description());
    }
    println!();
    println!("  Usage:");
    println!("    • Every ADR must have ≥1 relationship");
    println!("    • Tree roots use `Root: OWN-ID`");
    println!("    • Root + References cannot coexist (L009)");
    println!("    • Root + Supersedes may coexist");
    println!("    • Supersedes requires target status = `Superseded by PREFIX-NNNN`");
    println!();
    println!("  Legacy verbs (produce warnings):");
    for verb in RelVerb::legacy() {
        let migration = verb.migration().unwrap_or("remove");
        println!("    {verb:<15} → {migration}");
    }
    println!();
}

// ── Naming rules section ───────────────────────────────────────────

fn print_naming() {
    println!("NAMING");
    println!("──────");
    println!();
    println!("  Rules:");
    println!("    N001  Filename matches `PREFIX-NNNN-slug.md` pattern");
    println!("    N002  Prefix matches a configured domain");
    println!("    N003  Title ID matches filename ID");
    println!();
}

// ── Link rules section ─────────────────────────────────────────────

fn print_link_rules() {
    println!("LINK RULES");
    println!("──────────");
    println!();
    println!("  Rules:");
    println!("    L001  Dangling link — target ADR file not found");
    println!("    L003  Supersedes-status consistency");
    println!("    L007  Stale reference — link to stale archive ADR");
    println!("    L008  Root self-reference mismatch");
    println!("    L009  Root + References coexistence");
    println!();
}

// ── Stale section ──────────────────────────────────────────────────

fn print_stale(config: &Config) {
    println!("STALE DIRECTORY");
    println!("───────────────");
    println!();
    println!("  Path: {}/", config.stale.directory);
    println!("  ADRs in terminal states are moved here.");
    println!("  Each must include a ## Retirement section.");
    println!();
}

// ── Overrides section ──────────────────────────────────────────────

fn print_overrides(config: &Config) {
    if config.rules.is_empty() {
        return;
    }

    let has_params = config.rules.iter().any(|r| !r.params.is_empty());
    if !has_params {
        return;
    }

    println!("PARAMETER OVERRIDES");
    println!("───────────────────");
    println!();
    for rule in &config.rules {
        if rule.params.is_empty() {
            continue;
        }
        let pairs: Vec<String> = rule
            .params
            .iter()
            .map(|(k, v)| format!("{k}={v}"))
            .collect();
        println!("  {}  {}", rule.id, pairs.join(", "));
    }
    println!();
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_config() -> Config {
        toml::from_str(
            r#"
[stale]
directory = "stale"

[[domains]]
prefix = "COM"
name = "Common"
directory = "common"
description = "Cross-cutting design principles."
crates = []
foundation = true

[[domains]]
prefix = "CHE"
name = "Cherry"
directory = "cherry"
description = "Architecture decisions."
crates = ["cherry-pit-core"]

[[rules]]
id = "T015"
params = { min_words = 7, max_words = 50 }
"#,
        )
        .unwrap()
    }

    #[test]
    fn setup_guide_does_not_panic() {
        print_setup_guide();
    }

    #[test]
    fn governance_does_not_panic() {
        let config = make_config();
        print_governance(&config);
    }

    #[test]
    fn overrides_section_shown_when_params_exist() {
        let config = make_config();
        // Should not panic — overrides section will print T015 params
        print_overrides(&config);
    }

    #[test]
    fn overrides_section_hidden_when_no_params() {
        let config: Config = toml::from_str(
            r#"
[stale]
directory = "stale"

[[domains]]
prefix = "CHE"
name = "Cherry"
directory = "cherry"
description = "Test"
crates = []
"#,
        )
        .unwrap();
        // No rules at all → should not print anything
        print_overrides(&config);
    }
}
