//! Generates the complete ADR guidelines document from the rule catalog,
//! configuration, and code-level constants.
//!
//! Output is plain text to stdout. This replaces the prescriptive sections
//! of GOVERNANCE.md that were previously hand-maintained, making adr-fmt
//! the single source of truth for all invariant ADR governance rules.

use crate::config::Config;
use crate::model::{RelVerb, Status, Tier};

/// Print the complete guidelines document to stdout.
pub fn print(config: &Config) {
    print_header();
    print_domains(config);
    print_tiers();
    print_lifecycle();
    print_template_requirements(config);
    print_relationship_vocabulary();
    print_naming_rules(config);
    print_link_rules(config);
    print_structure_rules(config);
    print_stale_directory(config);
}

fn print_header() {
    println!("ADR Guidelines");
    println!("==============");
    println!();
    println!("Generated by adr-fmt from the rule catalog and configuration.");
    println!("This is the single source of truth for all invariant ADR governance rules.");
    println!("Configurable values are read from adr-fmt.toml.");
    println!();
    println!("For rationale, domain taxonomy justification, tier philosophy,");
    println!("and process guidance, see GOVERNANCE.md.");
    println!();
}

fn print_domains(config: &Config) {
    println!("DOMAINS");
    println!("-------");
    println!();
    for domain in &config.domains {
        let foundation_marker = if domain.foundation { " [foundation]" } else { "" };
        println!(
            "{name} ({prefix}){foundation_marker}",
            name = domain.name,
            prefix = domain.prefix,
        );
        println!("  Directory: {}", domain.directory);
        // Normalize whitespace in description
        let desc: String = domain.description.split_whitespace().collect::<Vec<_>>().join(" ");
        println!("  {desc}");
        if domain.crates.is_empty() {
            if domain.foundation {
                println!("  Crates: all (included with every domain query)");
            } else {
                println!("  Crates: none");
            }
        } else {
            println!("  Crates: {}", domain.crates.join(", "));
        }
        println!();
    }
}

fn print_tiers() {
    println!("TIERS");
    println!("-----");
    println!();
    for tier in Tier::all() {
        println!(
            "{tier:?} — {name}",
            name = tier.name(),
        );
        println!("  {}", tier.description());
        println!("  Stability: {}", tier.stability());
        println!("  Assignment: {} → Yes = {tier:?}", tier.assignment_guide());
        println!();
    }
}

fn print_lifecycle() {
    println!("LIFECYCLE STATES");
    println!("----------------");
    println!();
    let statuses = [
        Status::Draft,
        Status::Proposed,
        Status::Accepted,
        Status::Amended {
            date: None,
            note: None,
        },
        Status::Rejected,
        Status::Deprecated,
        Status::SupersededBy(crate::model::AdrId {
            prefix: "PREFIX".into(),
            number: 0,
        }),
    ];
    for status in &statuses {
        let name = match status {
            Status::Draft => "Draft",
            Status::Proposed => "Proposed",
            Status::Accepted => "Accepted",
            Status::Amended { .. } => "Amended [YYYY-MM-DD — note]",
            Status::Rejected => "Rejected",
            Status::Deprecated => "Deprecated",
            Status::SupersededBy(_) => "Superseded by PREFIX-NNNN",
            Status::Invalid(_) => unreachable!(),
        };
        let terminal = if status.is_terminal() {
            " [terminal]"
        } else {
            ""
        };
        println!("{name}{terminal}");
        println!("  {}", status.description());
    }
    println!();
    println!("Terminal states require:");
    println!("  1. Move ADR file to the stale directory");
    println!("  2. Add a `## Retirement` section explaining why the ADR left active service");
    println!();
}

fn print_template_requirements(config: &Config) {
    println!("TEMPLATE REQUIREMENTS");
    println!("---------------------");
    println!();
    println!("Every ADR must follow this structure:");
    println!();
    println!("  # PREFIX-NNNN. Title");
    println!();
    println!("  Date: YYYY-MM-DD");
    println!("  Last-reviewed: YYYY-MM-DD");
    println!("  Tier: S | A | B | C | D");
    println!();
    println!("  ## Status");
    println!("  ## Related");
    println!("  ## Context");
    println!("  ## Decision");
    println!("  ## Consequences");
    println!("  ## Retirement          (stale ADRs only)");
    println!();
    println!("Rules:");
    println!();
    for rule in &config.rules {
        if rule.internal {
            continue;
        }
        if rule.category == "template" {
            print_rule(rule);
        }
    }
    println!();
}

fn print_relationship_vocabulary() {
    println!("RELATIONSHIP VOCABULARY");
    println!("-----------------------");
    println!();
    println!("ADRs link toward the root of the dependency graph.");
    println!("Reverse links (parent listing children) are not stored;");
    println!("use `adr-fmt --report` to compute a children index on demand.");
    println!();
    println!("Permitted verbs (3):");
    println!();
    for verb in RelVerb::permitted() {
        println!("  {verb} — {}", verb.description());
    }
    println!();
    println!("Usage rules:");
    println!("  - Every ADR must have ≥1 relationship (no orphans)");
    println!("  - Tree roots use `- Root: OWN-ID`");
    println!("  - Root and References may not coexist");
    println!("  - Root and Supersedes may coexist (a root can supersede an older root)");
    println!("  - Supersedes requires setting the target's status to `Superseded by PREFIX-NNNN`");
    println!();
    println!("Legacy verbs (L006 warning):");
    println!();
    for verb in RelVerb::legacy() {
        let migration = verb.migration().unwrap_or("n/a");
        println!("  {verb} → {migration}");
    }
    println!();
}

fn print_naming_rules(config: &Config) {
    println!("NAMING RULES");
    println!("------------");
    println!();
    for rule in &config.rules {
        if rule.internal {
            continue;
        }
        if rule.category == "naming" {
            print_rule(rule);
        }
    }
    println!();
}

fn print_link_rules(config: &Config) {
    println!("LINK RULES");
    println!("----------");
    println!();
    for rule in &config.rules {
        if rule.internal {
            continue;
        }
        if rule.category == "link" {
            print_rule(rule);
        }
    }
    println!();
}

fn print_structure_rules(config: &Config) {
    println!("STRUCTURE RULES");
    println!("---------------");
    println!();
    for rule in &config.rules {
        if rule.internal {
            continue;
        }
        if rule.category == "structure" {
            print_rule(rule);
        }
    }
    println!();
}

fn print_stale_directory(config: &Config) {
    println!("STALE DIRECTORY");
    println!("---------------");
    println!();
    println!("Directory: {}/", config.stale.directory);
    println!("ADRs in terminal states (Rejected, Deprecated, Superseded) are moved here.");
    println!("Each must include a `## Retirement` section.");
    println!();
}

fn print_rule(rule: &crate::config::RuleConfig) {
    let params_str = if rule.params.is_empty() {
        String::new()
    } else {
        let pairs: Vec<String> = rule
            .params
            .iter()
            .map(|(k, v)| format!("{k}={v}"))
            .collect();
        format!(" ({})", pairs.join(", "))
    };
    println!("  {id} — {desc}{params_str}", id = rule.id, desc = rule.description);
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_config() -> Config {
        toml::from_str(
            r#"
[stale]
directory = "stale"

[[domains]]
prefix = "COM"
name = "Common Domain"
directory = "common"
description = "Cross-cutting design principles."
crates = []
foundation = true

[[domains]]
prefix = "CHE"
name = "Cherry Domain"
directory = "cherry"
description = "Architecture decisions."
crates = ["cherry-pit-core"]

[[rules]]
id = "T001"
category = "template"
description = "H1 title present"

[[rules]]
id = "T015"
category = "template"
description = "Prose section below minimum word count"
params = { min_words = 10 }

[[rules]]
id = "L001"
category = "link"
description = "Dangling link"

[[rules]]
id = "N001"
category = "naming"
description = "Filename matches pattern"

[[rules]]
id = "S004"
category = "structure"
description = "Stale ADR missing Retirement section"

[[rules]]
id = "I001"
category = "index"
description = "ADR file exists but not in README"
internal = true
"#,
        )
        .unwrap()
    }

    #[test]
    fn guidelines_covers_all_categories() {
        // Capture output by calling individual functions and verifying no panic
        let config = make_config();
        // These should all succeed without panicking
        print_header();
        print_domains(&config);
        print_tiers();
        print_lifecycle();
        print_template_requirements(&config);
        print_relationship_vocabulary();
        print_naming_rules(&config);
        print_link_rules(&config);
        print_structure_rules(&config);
        print_stale_directory(&config);
    }

    #[test]
    fn internal_rules_not_in_output() {
        let config = make_config();
        // Count non-internal rules that would be printed in template category
        let template_rules: Vec<_> = config
            .rules
            .iter()
            .filter(|r| !r.internal && r.category == "template")
            .collect();
        assert_eq!(template_rules.len(), 2); // T001, T015

        let index_rules: Vec<_> = config
            .rules
            .iter()
            .filter(|r| !r.internal && r.category == "index")
            .collect();
        assert_eq!(index_rules.len(), 0); // I001 is internal
    }
}
