//! Clock-driven token-bucket [`Regulator`](crate::Regulator) — increment B.
//!
//! Replaces the epoch-counter + single-elector-CAS + `Notify` park/wake
//! pacing path in [`BudgetGate`](crate::budget::BudgetGate) with a bucket
//! whose available-token count is a *pure function of elapsed clock
//! time*: `available(now) = min(capacity, generated(now) - consumed)`,
//! where `generated(now) = elapsed(now) * rate` grows without bound.
//! There is no elected resetter and no shared wakeup channel — every
//! caller independently recomputes its own deficit and retries, which is
//! what eliminates the F2 shared-election state-space (see
//! `spec/fizzbee/token_bucket.fizz`).
//!
//! RATE-only (CHE-0055 mission decision): this regulator paces call
//! *frequency*; it carries no concurrency-gauge concept, so
//! [`Regulator::settle`] is a no-op, matching
//! [`RateLimitRegulator`](crate::RateLimitRegulator).

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{Duration, Instant};

use tokio_util::sync::CancellationToken;

use crate::regulator::{Admission, Regulator};

/// Milli-token fixed-point scale: `consumed_milli` and `capacity_milli`
/// count thousandths of a token, so refill rates below one token per
/// second (e.g. one token per 4 seconds) still refill smoothly instead of
/// truncating to zero every tick.
const MILLI_PER_TOKEN: u64 = 1_000;

fn backdated_start_for_full_bucket(
    now: Instant,
    capacity_milli: u64,
    refill_milli_per_sec: u64,
) -> Instant {
    let fill_nanos =
        (u128::from(capacity_milli) * 1_000_000_000) / u128::from(refill_milli_per_sec);
    now.checked_sub(Duration::from_nanos(
        u64::try_from(fill_nanos).unwrap_or(u64::MAX),
    ))
    .unwrap_or(now)
}

/// An injectable time source for [`TokenBucketRegulator`].
///
/// Production code uses [`SystemClock`]. Tests inject a fake
/// implementation so refill assertions are deterministic — no wall-clock
/// sleeps in test assertions.
pub trait Clock: Send + Sync + 'static {
    /// The current instant, per this clock's notion of "now".
    fn now(&self) -> Instant;
}

/// [`Clock`] backed by [`Instant::now`].
#[derive(Debug, Default, Clone, Copy)]
pub struct SystemClock;

impl Clock for SystemClock {
    fn now(&self) -> Instant {
        Instant::now()
    }
}

/// Lock-free clock-driven token bucket, RATE-only.
///
/// Holds a single `AtomicU64` (`consumed_milli`); availability at any
/// instant is derived, never stored — `generated(now) - consumed`. No
/// other coordination state exists: no elected resetter, no `Notify`.
pub struct TokenBucketRegulator {
    clock: Arc<dyn Clock>,
    start: Instant,
    capacity_milli: u64,
    refill_milli_per_sec: u64,
    consumed_milli: AtomicU64,
}

impl TokenBucketRegulator {
    /// Construct a token bucket with the given capacity and refill rate
    /// (whole tokens), driven by `clock`.
    ///
    /// # Panics
    ///
    /// Panics if `capacity_tokens` or `refill_tokens_per_sec` is 0
    /// (would never admit / never refill), matching
    /// [`BudgetGate::new`](crate::budget::BudgetGate::new)'s invariant.
    #[must_use]
    pub fn new(clock: Arc<dyn Clock>, capacity_tokens: u64, refill_tokens_per_sec: u64) -> Self {
        assert!(capacity_tokens > 0, "token bucket capacity must be > 0");
        assert!(
            refill_tokens_per_sec > 0,
            "token bucket refill rate must be > 0"
        );
        let capacity_milli = capacity_tokens.saturating_mul(MILLI_PER_TOKEN);
        let refill_milli_per_sec = refill_tokens_per_sec.saturating_mul(MILLI_PER_TOKEN);
        let start =
            backdated_start_for_full_bucket(clock.now(), capacity_milli, refill_milli_per_sec);
        Self {
            clock,
            start,
            capacity_milli,
            refill_milli_per_sec,
            consumed_milli: AtomicU64::new(0),
        }
    }

    /// Tokens generated by `now` since construction, as a pure function
    /// of elapsed time (uncapped — grows without bound as time passes).
    /// No stored "last refill" state — recomputed from scratch every
    /// call, which is what makes the bucket coordination-free.
    fn uncapped_generated_milli_at(&self, now: Instant) -> u128 {
        let elapsed_nanos = now.saturating_duration_since(self.start).as_nanos();
        elapsed_nanos.saturating_mul(u128::from(self.refill_milli_per_sec)) / 1_000_000_000
    }

    /// Tokens generated by `now`, clamped to capacity — the bucket-full
    /// ceiling. This is a display/introspection view; [`Self::try_debit_one`]
    /// clamps `available` (generated-minus-consumed) instead, since
    /// clamping `generated` itself before subtracting the (permanently
    /// growing) `consumed` counter would strand availability at zero
    /// forever once `consumed` first reaches capacity.
    #[cfg(test)]
    fn generated_milli_at(&self, now: Instant) -> u64 {
        u64::try_from(self.uncapped_generated_milli_at(now))
            .unwrap_or(u64::MAX)
            .min(self.capacity_milli)
    }

    /// Attempt to debit one whole token via a single CAS on
    /// `consumed_milli`. `Ok` on success; `Err(wait)` with the pure
    /// duration until enough tokens will have accumulated, computed
    /// independently by this caller — no shared elected-resetter state,
    /// no `Notify` — every caller races the same lock-free CAS and, on
    /// deficit, sleeps its own computed wait before retrying.
    fn try_debit_one(&self) -> Result<(), Duration> {
        loop {
            let now = self.clock.now();
            let generated = self.uncapped_generated_milli_at(now);
            let consumed_u64 = self.consumed_milli.load(Ordering::Acquire);
            let consumed = u128::from(consumed_u64);
            let effective_consumed =
                consumed.max(generated.saturating_sub(u128::from(self.capacity_milli)));
            let available = generated.saturating_sub(effective_consumed);
            if available >= u128::from(MILLI_PER_TOKEN) {
                let Ok(next_consumed) =
                    u64::try_from(effective_consumed + u128::from(MILLI_PER_TOKEN))
                else {
                    return Err(Duration::MAX);
                };
                match self.consumed_milli.compare_exchange_weak(
                    consumed_u64,
                    next_consumed,
                    Ordering::AcqRel,
                    Ordering::Acquire,
                ) {
                    Ok(_) => return Ok(()),
                    Err(_) => continue,
                }
            }
            let deficit_milli = u128::from(MILLI_PER_TOKEN) - available;
            let wait_nanos =
                (deficit_milli * 1_000_000_000).div_ceil(u128::from(self.refill_milli_per_sec));
            return Err(Duration::from_nanos(
                u64::try_from(wait_nanos).unwrap_or(u64::MAX),
            ));
        }
    }
}

impl Regulator for TokenBucketRegulator {
    /// Loop: attempt a lock-free debit; on deficit, sleep the
    /// independently-computed wait and retry. No shared wakeup channel —
    /// each waiter's retry is driven purely by its own elapsed-time
    /// recomputation, which is what eliminates the F2 shared-election
    /// state space (`spec/fizzbee/token_bucket.fizz`).
    fn admit<'a>(
        &'a self,
        cancel: &'a CancellationToken,
    ) -> Pin<Box<dyn Future<Output = Admission> + Send + 'a>> {
        Box::pin(async move {
            loop {
                match self.try_debit_one() {
                    Ok(()) => return Admission::Admitted,
                    Err(wait) => {
                        tokio::select! {
                            () = tokio::time::sleep(wait) => {}
                            () = cancel.cancelled() => return Admission::Cancelled,
                        }
                    }
                }
            }
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::regulator::SettleOutcome;

    /// Deterministic clock for tests: an atomic nanosecond offset from a
    /// fixed base `Instant`, advanced explicitly — no wall-clock sleeps
    /// in assertions.
    struct FakeClock {
        base: Instant,
        offset_nanos: AtomicU64,
    }

    impl FakeClock {
        fn new() -> Arc<Self> {
            Arc::new(Self {
                base: Instant::now(),
                offset_nanos: AtomicU64::new(0),
            })
        }

        fn advance(&self, d: Duration) {
            self.offset_nanos.fetch_add(
                u64::try_from(d.as_nanos()).unwrap_or(u64::MAX),
                Ordering::Relaxed,
            );
        }
    }

    impl Clock for FakeClock {
        fn now(&self) -> Instant {
            self.base + Duration::from_nanos(self.offset_nanos.load(Ordering::Relaxed))
        }
    }

    #[test]
    fn generated_milli_is_pure_function_of_elapsed_time() {
        let clock = FakeClock::new();
        let bucket = TokenBucketRegulator::new(Arc::clone(&clock) as Arc<dyn Clock>, 10, 5);

        assert_eq!(
            bucket.generated_milli_at(clock.now()),
            10 * MILLI_PER_TOKEN,
            "bucket starts full"
        );

        assert!(bucket.try_debit_one().is_ok());
        let available =
            bucket.generated_milli_at(clock.now()) - bucket.consumed_milli.load(Ordering::Relaxed);
        assert_eq!(
            available,
            9 * MILLI_PER_TOKEN,
            "one debit reduces available by exactly one token"
        );

        clock.advance(Duration::from_secs(1));
        assert_eq!(
            bucket.generated_milli_at(clock.now()),
            10 * MILLI_PER_TOKEN,
            "generated stays clamped at capacity"
        );
    }

    #[test]
    fn constructs_with_valid_capacity_and_rate() {
        let bucket = TokenBucketRegulator::new(Arc::new(SystemClock), 10, 5);
        assert_eq!(bucket.capacity_milli, 10 * MILLI_PER_TOKEN);
        assert_eq!(bucket.refill_milli_per_sec, 5 * MILLI_PER_TOKEN);
    }

    #[test]
    #[should_panic(expected = "capacity must be > 0")]
    fn zero_capacity_panics() {
        let _ = TokenBucketRegulator::new(Arc::new(SystemClock), 0, 5);
    }

    #[test]
    #[should_panic(expected = "refill rate must be > 0")]
    fn zero_refill_rate_panics() {
        let _ = TokenBucketRegulator::new(Arc::new(SystemClock), 10, 0);
    }

    #[tokio::test]
    async fn admit_grants_immediately_within_capacity() {
        let clock = FakeClock::new();
        let bucket = TokenBucketRegulator::new(Arc::clone(&clock) as Arc<dyn Clock>, 2, 1);
        let cancel = CancellationToken::new();
        assert_eq!(bucket.admit(&cancel).await, Admission::Admitted);
        assert_eq!(bucket.admit(&cancel).await, Admission::Admitted);
    }

    #[test]
    fn try_debit_one_reports_pure_wait_then_succeeds_after_clock_advance() {
        let clock = FakeClock::new();
        let bucket = TokenBucketRegulator::new(Arc::clone(&clock) as Arc<dyn Clock>, 1, 1);
        assert!(bucket.try_debit_one().is_ok());

        let wait = bucket.try_debit_one().expect_err("bucket just emptied");
        assert_eq!(wait, Duration::from_secs(1));

        clock.advance(wait);
        assert!(
            bucket.try_debit_one().is_ok(),
            "advancing by exactly the reported wait must make the next debit succeed"
        );
    }

    #[tokio::test]
    async fn admit_grants_after_clock_advances_past_wait() {
        let clock = FakeClock::new();
        let bucket = TokenBucketRegulator::new(Arc::clone(&clock) as Arc<dyn Clock>, 1, 1);
        let cancel = CancellationToken::new();
        assert_eq!(bucket.admit(&cancel).await, Admission::Admitted);

        clock.advance(Duration::from_secs(1));
        assert_eq!(bucket.admit(&cancel).await, Admission::Admitted);
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 8)]
    async fn concurrent_debits_never_exceed_generated_capacity() {
        const CAPACITY_TOKENS: u64 = 5;
        const CONTENDERS: usize = 50;

        let clock = FakeClock::new();
        let bucket = Arc::new(TokenBucketRegulator::new(
            Arc::clone(&clock) as Arc<dyn Clock>,
            CAPACITY_TOKENS,
            1,
        ));

        let handles: Vec<_> = (0..CONTENDERS)
            .map(|_| {
                let bucket = Arc::clone(&bucket);
                tokio::spawn(async move { bucket.try_debit_one().is_ok() })
            })
            .collect();

        let mut successes = 0u64;
        for handle in handles {
            if handle.await.unwrap() {
                successes += 1;
            }
        }

        assert_eq!(
            successes, CAPACITY_TOKENS,
            "exactly the bucket's fixed capacity of concurrent debits must succeed"
        );
        assert_eq!(
            bucket.consumed_milli.load(Ordering::Relaxed),
            CAPACITY_TOKENS * MILLI_PER_TOKEN,
            "consumed must never exceed what was actually generated, even under contention"
        );
    }

    #[tokio::test]
    async fn admit_returns_cancelled_when_cancel_fires_while_waiting() {
        let clock = FakeClock::new();
        let bucket = TokenBucketRegulator::new(Arc::clone(&clock) as Arc<dyn Clock>, 1, 1);
        let cancel = CancellationToken::new();
        assert_eq!(bucket.admit(&cancel).await, Admission::Admitted);

        cancel.cancel();
        assert_eq!(bucket.admit(&cancel).await, Admission::Cancelled);
    }

    #[test]
    fn settle_uses_trait_default_no_op() {
        let bucket = TokenBucketRegulator::new(Arc::new(SystemClock), 5, 5);
        bucket.settle(SettleOutcome::Charged);
        bucket.settle(SettleOutcome::Free);
    }

    #[test]
    fn arbitrary_idle_gap_caps_immediate_burst_to_capacity() {
        let clock = FakeClock::new();
        let bucket = TokenBucketRegulator::new(Arc::clone(&clock) as Arc<dyn Clock>, 5, 1);
        clock.advance(Duration::from_secs(3600));

        for _ in 0..5 {
            assert!(bucket.try_debit_one().is_ok());
        }

        let wait = bucket
            .try_debit_one()
            .expect_err("sixth call after idle gap must be rejected");
        assert_eq!(wait, Duration::from_secs(1));
    }

    proptest::proptest! {
        #[test]
        fn prop_idle_gap_caps_burst_to_capacity(
            capacity in 1u64..20u64,
            refill_rate in 1u64..10u64,
            idle_secs in 1u64..10_000u64,
        ) {
            let clock = FakeClock::new();
            let bucket = TokenBucketRegulator::new(
                Arc::clone(&clock) as Arc<dyn Clock>,
                capacity,
                refill_rate,
            );
            clock.advance(Duration::from_secs(idle_secs));

            for _ in 0..capacity {
                proptest::prop_assert!(bucket.try_debit_one().is_ok());
            }

            let wait = bucket.try_debit_one();
            proptest::prop_assert!(wait.is_err());
        }
    }

    #[test]
    fn high_refill_rate_counter_overflow_fails_closed_without_unmetered_admissions() {
        let clock = FakeClock::new();
        let bucket = TokenBucketRegulator::new(
            Arc::clone(&clock) as Arc<dyn Clock>,
            1,
            u64::MAX / MILLI_PER_TOKEN,
        );
        clock.advance(Duration::from_secs(2));

        assert_eq!(bucket.try_debit_one(), Err(Duration::MAX));

        for _ in 0..10 {
            assert_eq!(bucket.try_debit_one(), Err(Duration::MAX));
        }
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 8)]
    async fn concurrent_debits_after_arbitrary_idle_admit_exactly_capacity() {
        const CAPACITY_TOKENS: u64 = 5;
        const CONTENDERS: usize = 50;

        let clock = FakeClock::new();
        let bucket = Arc::new(TokenBucketRegulator::new(
            Arc::clone(&clock) as Arc<dyn Clock>,
            CAPACITY_TOKENS,
            1,
        ));
        clock.advance(Duration::from_hours(4));

        let handles: Vec<_> = (0..CONTENDERS)
            .map(|_| {
                let bucket = Arc::clone(&bucket);
                tokio::spawn(async move { bucket.try_debit_one().is_ok() })
            })
            .collect();

        let mut successes = 0u64;
        for handle in handles {
            if handle.await.unwrap() {
                successes += 1;
            }
        }

        assert_eq!(
            successes, CAPACITY_TOKENS,
            "exactly the bucket's fixed capacity of concurrent debits must succeed after multi-hour idle"
        );
        assert!(
            bucket.try_debit_one().is_err(),
            "immediate debit after exhausted burst must be rejected"
        );
    }
}
